name: sahl_edu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2
  flutter_svg: ^1.1.6
  auto_size_text: ^3.0.0

  # DI & State management
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1

  # Network
  dio: ^4.0.6
  http_parser: ^4.0.2
  pretty_dio_logger: ^1.2.0-beta-1
  connectivity_plus: ^3.0.2

  # Local
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^7.0.1

  # Utils
  dartz: ^0.10.1

  # Firebase
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.1
  firebase_storage: ^11.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300